import { useCallback, useEffect, useState } from 'react'
import { ActivityIndicator, Button, FlatList, Image, KeyboardAvoidingView, Linking, Platform, StyleSheet, Text, TextInput, View } from 'react-native'
import * as DocumentPicker from 'expo-document-picker'
import * as ImagePicker from 'expo-image-picker'
import { supabase } from '../lib/supabase'

type Attachment={id:string;message_id:string;storage_path:string;file_name:string;file_type:string;file_size:number;url?:string}
type Message={id:string;sender_id:string;content:string|null;created_at:string;deleted_at:string|null;updated_at:string;reply_to:string|null}
type PendingFile={uri:string;name:string;type:string;size:number}
const IMAGE_TYPES=new Set(['image/jpeg','image/png','image/webp']),FILE_TYPES=new Set(['application/pdf','text/plain','application/zip','application/octet-stream']),MAX_IMAGE=5*1024*1024,MAX_FILE=50*1024*1024

export default function GroupThreadScreen({groupId,title,onBack}:{groupId:string;title:string;onBack:()=>void}){
 const[messages,setMessages]=useState<Message[]>([]),[attachments,setAttachments]=useState<Record<string,Attachment[]>>({}),[text,setText]=useState(''),[userId,setUserId]=useState<string|null>(null),[loading,setLoading]=useState(true),[sending,setSending]=useState(false),[pending,setPending]=useState<PendingFile|null>(null),[replyTo,setReplyTo]=useState<Message|null>(null),[editing,setEditing]=useState<Message|null>(null)
 const loadAttachments=useCallback(async(items:Message[])=>{const ids=items.map(m=>m.id);if(!ids.length)return;const{data}=await supabase.from('group_message_attachments').select('id,message_id,storage_path,file_name,file_type,file_size').in('message_id',ids);if(!data)return;const grouped:Record<string,Attachment[]>={};for(const a of data as Attachment[]){const bucket=IMAGE_TYPES.has(a.file_type)?'group-images':'chat-files';const{data:signed}=await supabase.storage.from(bucket).createSignedUrl(a.storage_path,3600);(grouped[a.message_id]??=[]).push({...a,url:signed?.signedUrl})}setAttachments(current=>({...current,...grouped}))},[])
 const load=useCallback(async()=>{const{data:auth}=await supabase.auth.getUser();if(!auth.user)return;setUserId(auth.user.id);const{data}=await supabase.from('group_messages').select('id,sender_id,content,created_at,deleted_at,updated_at,reply_to').eq('group_id',groupId).order('created_at',{ascending:true}).limit(100);const items=(data??[]) as Message[];setMessages(items);void loadAttachments(items);setLoading(false)},[groupId,loadAttachments])
 useEffect(()=>{void load()},[load]);useEffect(()=>{const c=supabase.channel(`mobile-group-thread:${groupId}`).on('postgres_changes',{event:'*',schema:'public',table:'group_messages',filter:`group_id=eq.${groupId}`},()=>void load()).subscribe();return()=>{void supabase.removeChannel(c)}},[groupId,load])
 async function pickImage(){const permission=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted)return;const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:0.9});if(result.canceled)return;const a=result.assets[0];setPending({uri:a.uri,name:a.fileName??`image-${Date.now()}.jpg`,type:a.mimeType??'image/jpeg',size:a.fileSize??0})}
 async function pickFile(){const result=await DocumentPicker.getDocumentAsync({type:['application/pdf','text/plain','application/zip','application/octet-stream'],copyToCacheDirectory:true});if(result.canceled)return;const a=result.assets[0];setPending({uri:a.uri,name:a.name,type:a.mimeType??'application/octet-stream',size:a.size??0})}
 async function send(){const content=text.trim();if((!content&&!pending)||!userId||sending)return;setSending(true);if(editing){const{error}=await supabase.from('group_messages').update({content,updated_at:new Date().toISOString()}).eq('id',editing.id).eq('sender_id',userId);setSending(false);if(!error){setText('');setEditing(null);void load()}return}let uploaded:{path:string;bucket:string}|null=null;if(pending){const isImage=IMAGE_TYPES.has(pending.type),allowed=isImage||FILE_TYPES.has(pending.type),max=isImage?MAX_IMAGE:MAX_FILE;if(!allowed||pending.size<=0||pending.size>max){setSending(false);return}const bucket=isImage?'group-images':'chat-files',safe=pending.name.replace(/[^a-zA-Z0-9._-]/g,'_').slice(-100)||'attachment',path=`${groupId}/${Date.now()}-${safe}`,response=await fetch(pending.uri),body=await response.arrayBuffer(),upload=await supabase.storage.from(bucket).upload(path,body,{contentType:pending.type,upsert:false});if(upload.error){setSending(false);return}uploaded={path,bucket}}
 const{data,error}=await supabase.from('group_messages').insert({group_id:groupId,sender_id:userId,content:content||null,reply_to:replyTo?.id??null}).select('id,sender_id,content,created_at,deleted_at,updated_at,reply_to').single();if(error||!data){if(uploaded)await supabase.storage.from(uploaded.bucket).remove([uploaded.path]);setSending(false);return}const message=data as Message;if(uploaded){const{error:attachmentError}=await supabase.from('group_message_attachments').insert({message_id:message.id,storage_path:uploaded.path,file_name:pending!.name,file_type:pending!.type,file_size:pending!.size});if(attachmentError){await supabase.from('group_messages').delete().eq('id',message.id);await supabase.storage.from(uploaded.bucket).remove([uploaded.path]);setSending(false);return}}setText('');setPending(null);setReplyTo(null);setSending(false);void load()}
 async function removeMessage(m:Message){if(!userId||m.sender_id!==userId)return;const{error}=await supabase.from('group_messages').update({deleted_at:new Date().toISOString(),content:null}).eq('id',m.id).eq('sender_id',userId);if(!error)void load()}
 if(loading)return <View style={styles.center}><ActivityIndicator/></View>
 return <KeyboardAvoidingView style={styles.container} behavior={Platform.OS==='ios'?'padding':undefined}><View style={styles.header}><Button title="Back" onPress={onBack}/><Text style={styles.title}>{title}</Text></View><FlatList data={messages} keyExtractor={m=>m.id} contentContainerStyle={styles.list} renderItem={({item})=>{const mine=item.sender_id===userId,parent=item.reply_to?messages.find(m=>m.id===item.reply_to):null,files=attachments[item.id]??[];return <View style={[styles.bubble,mine&&styles.mine]}>{parent&&<Text style={styles.reply}>↪ {parent.content??'Attachment message'}</Text>}{files.map(a=>a.url&&IMAGE_TYPES.has(a.file_type)?<Image key={a.id} source={{uri:a.url}} style={styles.image}/>:<Text key={a.id} style={styles.file} onPress={()=>a.url&&void Linking.openURL(a.url)}>📎 {a.file_name}</Text>)}{item.deleted_at?<Text>Message deleted</Text>:item.content&&<Text>{item.content}</Text>}<Text style={styles.time}>{new Date(item.created_at).toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'})}</Text>{!item.deleted_at&&<View style={styles.actions}><Button title="Reply" onPress={()=>{setReplyTo(item);setEditing(null)}}/>{mine&&<><Button title="Edit" onPress={()=>{setEditing(item);setReplyTo(null);setText(item.content??'')}}/><Button title="Delete" onPress={()=>void removeMessage(item)}/></>}</View>}</View>}} ListEmptyComponent={<Text style={styles.empty}>No group messages yet.</Text>}/>{(replyTo||editing||pending)&&<View style={styles.preview}>{editing?<Text>Editing message</Text>:replyTo?<Text>Replying to: {replyTo.content??'attachment'}</Text>:null}{pending&&<Text>📎 {pending.name}</Text>}<Button title="Cancel" onPress={()=>{setReplyTo(null);setEditing(null);setPending(null)}}/></View>}<View style={styles.composer}><View style={styles.tools}><Button title="📷" onPress={()=>void pickImage()}/><Button title="📎" onPress={()=>void pickFile()}/></View><TextInput placeholder="Message group" value={text} onChangeText={setText} multiline style={styles.input}/><Button title={sending?'…':editing?'Save':'Send'} onPress={()=>void send()} disabled={sending}/></View></KeyboardAvoidingView>
}
const styles=StyleSheet.create({container:{flex:1},center:{flex:1,alignItems:'center',justifyContent:'center'},header:{flexDirection:'row',alignItems:'center',gap:8,padding:10,borderBottomWidth:1,borderColor:'#ddd'},title:{fontSize:20,fontWeight:'600'},list:{padding:14,gap:8},bubble:{alignSelf:'flex-start',maxWidth:'84%',padding:10,borderRadius:12,borderWidth:1,borderColor:'#ddd'},mine:{alignSelf:'flex-end'},reply:{fontSize:12,opacity:.65,marginBottom:5},image:{width:220,height:180,borderRadius:10,marginBottom:6},file:{paddingVertical:5,textDecorationLine:'underline'},time:{fontSize:10,opacity:.55,marginTop:4},actions:{flexDirection:'row',marginTop:4},empty:{textAlign:'center',marginTop:30,opacity:.6},preview:{padding:8,borderTopWidth:1,borderColor:'#ddd'},composer:{flexDirection:'row',alignItems:'flex-end',gap:4,padding:10,borderTopWidth:1,borderColor:'#ddd'},tools:{flexDirection:'row'},input:{flex:1,borderWidth:1,borderColor:'#ccc',borderRadius:10,padding:10,maxHeight:100}})
