import { useCallback, useEffect, useState } from 'react'
import { ActivityIndicator, Button, FlatList, KeyboardAvoidingView, Platform, StyleSheet, Text, TextInput, View } from 'react-native'
import { supabase } from '../lib/supabase'

type Message = { id: string; sender_id: string; content: string | null; created_at: string; deleted_at: string | null }
export default function MessageThreadScreen({ conversationId, title, onBack }: { conversationId: string; title: string; onBack: () => void }) {
 const [messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(''),[userId,setUserId]=useState<string|null>(null),[loading,setLoading]=useState(true),[sending,setSending]=useState(false)
 const load=useCallback(async()=>{const {data:auth}=await supabase.auth.getUser();if(!auth.user)return;setUserId(auth.user.id);const {data}=await supabase.from('messages').select('id,sender_id,content,created_at,deleted_at').eq('conversation_id',conversationId).order('created_at',{ascending:true}).limit(100);setMessages(data??[]);await supabase.rpc('mark_conversation_read',{p_conversation_id:conversationId});setLoading(false)},[conversationId])
 useEffect(()=>{void load()},[load]);useEffect(()=>{const c=supabase.channel(`mobile-message-thread:${conversationId}`).on('postgres_changes',{event:'*',schema:'public',table:'messages',filter:`conversation_id=eq.${conversationId}`},()=>void load()).subscribe();return()=>{void supabase.removeChannel(c)}},[conversationId,load])
 async function send(){const content=text.trim();if(!content||!userId||sending)return;setSending(true);const {error}=await supabase.from('messages').insert({conversation_id:conversationId,sender_id:userId,content,message_type:'text'});setSending(false);if(!error){setText('');void load()}}
 if(loading)return <View style={styles.center}><ActivityIndicator/></View>
 return <KeyboardAvoidingView style={styles.container} behavior={Platform.OS==='ios'?'padding':undefined}><View style={styles.header}><Button title="Back" onPress={onBack}/><Text style={styles.title}>{title}</Text></View><FlatList data={messages} keyExtractor={m=>m.id} contentContainerStyle={styles.list} renderItem={({item})=><View style={[styles.bubble,item.sender_id===userId&&styles.mine]}><Text>{item.deleted_at?'Message deleted':item.content}</Text></View>} ListEmptyComponent={<Text style={styles.empty}>No messages yet.</Text>}/><View style={styles.composer}><TextInput placeholder="Message" value={text} onChangeText={setText} multiline style={styles.input}/><Button title={sending?'…':'Send'} onPress={()=>void send()} disabled={sending}/></View></KeyboardAvoidingView>
}
const styles=StyleSheet.create({container:{flex:1},center:{flex:1,alignItems:'center',justifyContent:'center'},header:{flexDirection:'row',alignItems:'center',gap:8,padding:10,borderBottomWidth:1,borderColor:'#ddd'},title:{fontSize:20,fontWeight:'600'},list:{padding:14,gap:8},bubble:{alignSelf:'flex-start',maxWidth:'82%',padding:10,borderRadius:12,borderWidth:1,borderColor:'#ddd'},mine:{alignSelf:'flex-end'},empty:{textAlign:'center',marginTop:30,opacity:.6},composer:{flexDirection:'row',alignItems:'flex-end',gap:8,padding:10,borderTopWidth:1,borderColor:'#ddd'},input:{flex:1,borderWidth:1,borderColor:'#ccc',borderRadius:10,padding:10,maxHeight:100}})
