import { useCallback, useEffect, useState } from 'react'
import { ActivityIndicator, Button, FlatList, Image, KeyboardAvoidingView, Linking, Platform, StyleSheet, Text, TextInput, View } from 'react-native'
import * as DocumentPicker from 'expo-document-picker'
import * as ImagePicker from 'expo-image-picker'
import { supabase } from '../lib/supabase'

type Attachment={id:string;message_id:string;storage_path:string;file_name:string;file_type:string;file_size:number;url?:string}
type Message={id:string;sender_id:string;content:string|null;message_type:string;reply_to:string|null;created_at:string;updated_at:string;deleted_at:string|null}
type PendingFile={uri:string;name:string;type:string;size:number}
const IMAGE_TYPES=new Set(['image/jpeg','image/png','image/webp','image/gif']),FILE_TYPES=new Set(['application/pdf','text/plain','application/zip','application/octet-stream']),MAX_IMAGE=15*1024*1024,MAX_FILE=50*1024*1024

export default function MessageThreadScreen({conversationId,title,onBack}:{conversationId:string;title:string;onBack:()=>void}){
 const[messages,setMessages]=useState<Message[]>([]),[attachments,setAttachments]=useState<Record<string,Attachment[]>>({}),[text,setText]=useState(''),[userId,setUserId]=useState<string|null>(null),[loading,setLoading]=useState(true),[sending,setSending]=useState(false),[pending,setPending]=useState<PendingFile|null>(null),[replyTo,setReplyTo]=useState<Message|null>(null),[editing,setEditing]=useState<Message|null>(null),[readIds,setReadIds]=useState<Set<string>>(new Set())
 const loadAttachments=useCallback(async(items:Message[])=>{const ids=items.map(m=>m.id);if(!ids.length)return;const{data}=await supabase.from('message_attachments').select('id,message_id,storage_path,file_name,file_type,file_size').in('message_id',ids);if(!data)return;const grouped:Record<string,Attachment[]>={};for(const a of data as Attachment[]){const bucket=IMAGE_TYPES.has(a.file_type)?'chat-images':'chat-files';const{data:signed}=await supabase.storage.from(bucket).createSignedUrl(a.storage_path,3600);(grouped[a.message_id]??=[]).push({...a,url:signed?.signedUrl})}setAttachments(current=>({...current,...grouped}))},[])
 const load=useCallback(async()=>{const{data:auth}=await supabase.auth.getUser();if(!auth.user)return;setUserId(auth.user.id);const{data}=await supabase.from('messages').select('id,sender_id,content,message_type,reply_to,created_at,updated_at,deleted_at').eq('conversation_id',conversationId).order('created_at',{ascending:true}).limit(100);const items=(data??[]) as Message[];setMessages(items);await Promise.all([loadAttachments(items),supabase.rpc('mark_conversation_read',{p_conversation_id:conversationId})]);const own=items.filter(m=>m.sender_id===auth.user.id).map(m=>m.id);if(own.length){const{data:reads}=await supabase.from('message_reads').select('message_id,user_id').in('message_id',own).neq('user_id',auth.user.id);if(reads)setReadIds(new Set(reads.map(r=>r.message_id)))}setLoading(false)},[conversationId,loadAttachments])
 useEffect(()=>{void load()},[load])
 useEffect(()=>{const c=supabase.channel(`mobile-message-thread:${conversationId}`).on('postgres_changes',{event:'*',schema:'public',table:'messages',filter:`conversation_id=eq.${conversationId}`},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'message_reads'},payload=>{const row=payload.new as{message_id:string;user_id:string};if(row.user_id!==userId)setReadIds(current=>new Set(current).add(row.message_id))}).subscribe();return()=>{void supabase.removeChannel(c)}},[conversationId,load,userId])
 async function pickImage(){const permission=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted)return;const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:0.9});if(result.canceled)return;const a=result.assets[0];setPending({uri:a.uri,name:a.fileName??`image-${Date.now()}.jpg`,type:a.mimeType??'image/jpeg',size:a.fileSize??0})}
 async function pickFile(){const result=await DocumentPicker.getDocumentAsync({type:['application/pdf','text/plain','application/zip','application/octet-stream'],copyToCacheDirectory:true});if(result.canceled)return;const a=result.assets[0];setPending({uri:a.uri,name:a.name,type:a.mimeType??'application/octet-stream',size:a.size??0})}
 async function send(){const content=text.trim();if((!content&&!pending)||!userId||sending)return;setSending(true);if(editing){const{error}=await supabase.from('messages').update({content,updated_at:new Date().toISOString()}).eq('id',editing.id).eq('sender_id',userId);setSending(false);if(!error){setText('');setEditing(null);void load()}return}let uploaded:{path:string;bucket:string}|null=null;if(pending){const isImage=IMAGE_TYPES.has(pending.type),allowed=isImage||FILE_TYPES.has(pending.type),max=isImage?MAX_IMAGE:MAX_FILE;if(!allowed||pending.size<=0||pending.size>max){setSending(false);return}const bucket=isImage?'chat-images':'chat-files',safe=pending.name.replace(/[^a-zA-Z0-9._-]/g,'_').slice(-100)||'attachment',path=`${conversationId}/${Date.now()}-${safe}`,response=await fetch(pending.uri),body=await response.arrayBuffer(),upload=await supabase.storage.from(bucket).upload(path,body,{contentType:pending.type,upsert:false});if(upload.error){setSending(false);return}uploaded={path,bucket}}
 const type=uploaded?(IMAGE_TYPES.has(pending!.type)?'image':pending!.type==='application/pdf'?'pdf':'file'):'text';const{data,error}=await supabase.from('messages').insert({conversation_id:conversationId,sender_id:userId,content:content||null,message_type:type,reply_to:replyTo?.id??null}).select('id,sender_id,content,message_type,reply_to,created_at,updated_at,deleted_at').single();if(error||!data){if(uploaded)await supabase.storage.from(uploaded.bucket).remove([uploaded.path]);setSending(false);return}const message=data as Message;if(uploaded){const{error:attachmentError}=await supabase.from('message_attachments').insert({message_id:message.id,storage_path:uploaded.path,file_name:pending!.name,file_type:pending!.type,file_size:pending!.size});if(attachmentError){await supabase.from('messages').delete().eq('id',message.id);await supabase.storage.from(uploaded.bucket).remove([uploaded.path]);setSending(false);return}}setText('');setPending(null);setReplyTo(null);setSending(false);void load()}
 async function removeMessage(m:Message){if(!userId||m.sender_id!==userId)return;const{error}=await supabase.from('messages').update({deleted_at:new Date().toISOString(),content:null}).eq('id',m.id).eq('sender_id',userId);if(!error)void load()}
 if(loading)return <View style={styles.center}><ActivityIndicator/></View>
 return <KeyboardAvoidingView style={styles.container} behavior={Platform.OS==='ios'?'padding':undefined}><View style={styles.header}><Button title="Back" onPress={onBack}/><Text style={styles.title}>{title}</Text></View><FlatList data={messages} keyExtractor={m=>m.id} contentContainerStyle={styles.list} renderItem={({item})=>{const mine=item.sender_id===userId,parent=item.reply_to?messages.find(m=>m.id===item.reply_to):null,files=attachments[item.id]??[];return <View style={[styles.bubble,mine&&styles.mine]}>{parent&&<Text style={styles.reply}>↪ {parent.content??'Attachment message'}</Text>}{files.map(a=>a.url&&IMAGE_TYPES.has(a.file_type)?<Image key={a.id} source={{uri:a.url}} style={styles.image}/>:<Text key={a.id} style={styles.file} onPress={()=>a.url&&void Linking.openURL(a.url)}>📎 {a.file_name}</Text>)}{item.deleted_at?<Text>Message deleted</Text>:item.content&&<Text>{item.content}</Text>}<View style={styles.meta}><Text style={styles.time}>{new Date(item.created_at).toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'})}</Text>{mine&&<Text>{readIds.has(item.id)?'✓✓':'✓'}</Text>}</View>{!item.deleted_at&&<View style={styles.actions}><Button title="Reply" onPress={()=>{setReplyTo(item);setEditing(null)}}/>{mine&&<><Button title="Edit" onPress={()=>{setEditing(item);setReplyTo(null);setText(item.content??'')}}/><Button title="Delete" onPress={()=>void removeMessage(item)}/></>}</View>}</View>}} ListEmptyComponent={<Text style={styles.empty}>No messages yet.</Text>}/>{(replyTo||editing||pending)&&<View style={styles.preview}>{editing?<Text>Editing message</Text>:replyTo?<Text>Replying to: {replyTo.content??'attachment'}</Text>:null}{pending&&<Text>📎 {pending.name}</Text>}<Button title="Cancel" onPress={()=>{setReplyTo(null);setEditing(null);setPending(null)}}/></View>}<View style={styles.composer}><View style={styles.tools}><Button title="📷" onPress={()=>void pickImage()}/><Button title="📎" onPress={()=>void pickFile()}/></View><TextInput placeholder="Message" value={text} onChangeText={setText} multiline style={styles.input}/><Button title={sending?'…':editing?'Save':'Send'} onPress={()=>void send()} disabled={sending}/></View></KeyboardAvoidingView>
}
const styles=StyleSheet.create({container:{flex:1},center:{flex:1,alignItems:'center',justifyContent:'center'},header:{flexDirection:'row',alignItems:'center',gap:8,padding:10,borderBottomWidth:1,borderColor:'#ddd'},title:{fontSize:20,fontWeight:'600'},list:{padding:14,gap:8},bubble:{alignSelf:'flex-start',maxWidth:'84%',padding:10,borderRadius:12,borderWidth:1,borderColor:'#ddd'},mine:{alignSelf:'flex-end'},reply:{fontSize:12,opacity:.65,marginBottom:5},image:{width:220,height:180,borderRadius:10,marginBottom:6},file:{paddingVertical:5,textDecorationLine:'underline'},meta:{flexDirection:'row',justifyContent:'flex-end',gap:5,marginTop:4},time:{fontSize:10,opacity:.55},actions:{flexDirection:'row',marginTop:4},empty:{textAlign:'center',marginTop:30,opacity:.6},preview:{padding:8,borderTopWidth:1,borderColor:'#ddd'},composer:{flexDirection:'row',alignItems:'flex-end',gap:4,padding:10,borderTopWidth:1,borderColor:'#ddd'},tools:{flexDirection:'row'},input:{flex:1,borderWidth:1,borderColor:'#ccc',borderRadius:10,padding:10,maxHeight:100}})
